FINANCIERA/urls.py
from django.contrib import admin
from django.urls import path, include
from FINANCIERA.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name="INICIO"),
    path('about/', about, name="ABOUT"),
    path('AppComercios/', include('AppComercios.urls')),
    path('AppCreditos/', include('AppCreditos.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCreditos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CRE(models.Model):
    
    def __str__(self):
        return f'Nombre: {self.nombre} / Apellido: {self.apellido} / DNI: {self.dni}'
    
    nombre = models.CharField(max_length=25)
    apellido = models.CharField(max_length=25)
    dni = models.IntegerField()
    fecha_nac = models.DateField()
    telefono = models.IntegerField()
    fecha_cred = models.DateField()
    importe = models.FloatField()
    cuotas = models.IntegerField()


class RES(models.Model):

    usuario = models.CharField(max_length=25)
    comercio_res = models.CharField(max_length=25)
    comentario = models.CharField(max_length=200)
    

class IMG(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)
    

FINANCIERA/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Template, Context, loader

# PAGINA DE INCIO ---------------------------------------------------

def inicio(request):
    return render(request,'FINANCIERA/templates/inicio.html')

# ACERCA DE MI -----------------------------------------------------

def about(request):
    return render(request,'FINANCIERA/templates/about.html')

FINANCIERA/templates/about.html
{% extends 'AppCreditos/padre.html' %}

{% load static %}

{% block titulo %}
ACERCA DE MI
{% endblock %}

{% block formCarga %} 

Mi nombre es Carlos Quinteros y vivo en la ciudad de Santa Fe (Argentina). Soy Admnistrador de Empresas con una fuerte orientación y pasión por los datos.<br>
Actualmente trabajo para una financiera local, ocupando el puesto de Responsable de Recupero y adicionalmente me encargo de la explotación de los datos de 
la empresa para generar conocimiento.<br>
Este acercamiento a los datos y sus herramientas hizo interesarme tambien por la programación, buscando profundizar mis conocimientos en Python y en la programacion web.<br>
Este es mi proyecto final del curso (y mi prmer pagina we realizada!) de Python y Django de Coderhouse.<br>
Bienvenidos a mi web!


<hr class="divider" />
<a class="btn btn-primary btn-xl" href="{% url 'INICIO' %}">Inicio</a>
{% endblock %}

FINANCIERA/templates/inicio.html
{% extends 'AppCreditos/padre.html' %}

{% load static %}

{% block titulo %}
<h1 class="text-white font-weight-bold">{{mensaje}}<br>Bienvenido a Financiera S.A.</h1>
{% endblock %}

{% block formCarga %} 

    <p class="text-white-75 mb-5">Con FINANCIERA S.A. accedé a los micro-créditos con la tasa más baja del mercado en más de 100 comercios de la ciudad de 
        Santa Fe (Argentina). <br>Buscá eso que tanto querés en nuestros comercios adheridos y hacé tu pedido de crédito online con mínimos requisitos. <br>Una vez
        que hagas tu pedido un asesor se va a contactar con vos para finalizar tu gestión.</p>
    <a class="btn btn-primary btn-xl" href="{% url 'INI_CLI' %}">CLIENTES</a>
    <a class="btn btn-primary btn-xl" href="{% url 'INI_COMER' %}">COMERCIOS</a>
</div>
</div>
</div>
</header>
<!-- About-->
<section class="page-section bg-primary" id="about">
<div class="container px-4 px-lg-5">
<div class="row gx-4 gx-lg-5 justify-content-center">
<div class="col-lg-8 text-center">
    <h2 class="text-white mt-0">Mirá los distintos rubros de los comercios aheridos que tenemos para vos!</h2>
    <hr class="divider divider-light" />
    <!--<p class="text-white-75 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
    <a class="btn btn-light btn-xl" href="#services">Get Started!</a>-->
</div>
</div>
</div>
</section>
<!-- Portfolio-->
<div id="portfolio">
<div class="container-fluid p-0">
<div class="row g-0">
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/1.jpg' %}" title="Indumentaria">
        <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/1.jpg' %}" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Rubro</div>
            <div class="project-name">Indumentaria</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/2.jpg' %}" title="Calzado">
        <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/2.jpg' %}" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Rubro</div>
            <div class="project-name">Calzado</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/3.jpg' %}" title="Deportes">
        <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/3.jpg' %}" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Rubro</div>
            <div class="project-name">Deportes</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/4.jpg' %}" title="Electrodomésticos">
        <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/4.jpg' %}" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Rubro</div>
            <div class="project-name">Electrodomésticos</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/5.jpg' %}" title="Dormitorio">
        <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/5.jpg' %}" alt="..." />
        <div class="portfolio-box-caption">
            <div class="project-category text-white-50">Rubro</div>
            <div class="project-name">Dormitorio</div>
        </div>
    </a>
</div>
<div class="col-lg-4 col-sm-6">
    <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/6.jpg' %}" title="Materiales">
        <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/6.jpg' %}" alt="..." />
        <div class="portfolio-box-caption p-3">
            <div class="project-category text-white-50">Rubro</div>
            <div class="project-name">Materiales</div>
        </div>
    </a>
</div>
</div>
</div>
</div>

<!-- Footer-->
<footer class="bg-light py-5">
<div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2022 - Carlos Quinteros</div></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'AppCreditos/js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

{% endblock %}

FINANCIERA/templates/pr2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppCreditos/assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCreditos/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'INICIO' %}">Inicio</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">Acerca de mi</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'INI_CLI' %}">Clientes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'INI_COMER' %}">Comercios</a></li>
                        
                        {% if request.user.is_authenticated %}
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'EDIT_USR' %}">Editar</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'LOGOUT' %}">Salir</a></li>
                        &nbsp;&nbsp;<p class="text-white-75 mb-5">Hola {{user.username}}</p>&nbsp;&nbsp;
                        
                        {% with first_image=user.img_set.first %}

                        {% if first_image %}

                        <img src="{{first_image.imagen.url}}" width="41" height="38">

                        {% endif %}

                        {% endwith %}

                        {% else %} 

                        <li class="nav-item"><a class="nav-link" href="{% url 'LOGIN' %}">Ingresar</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'REGISTRO' %}">Registrarse</a></li>

                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">{{mensaje}}<br>Bienvenido a Financiera S.A.</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">Con FINANCIERA S.A. accedé a los micro-créditos con la tasa más baja del mercado en más de 100 comercios de la ciudad de 
                            Santa Fe (Argentina). <br>Buscá eso que tanto querés en nuestros comercios adheridos y hacé tu pedido de crédito online con mínimos requisitos. <br>Una vez
                            que hagas tu pedido un asesor se va a contactar con vos para finalizar tu gestión.</p>
                        <a class="btn btn-primary btn-xl" href="{% url 'INI_CLI' %}">CLIENTES</a>
                        <a class="btn btn-primary btn-xl" href="{% url 'INI_COMER' %}">COMERCIOS</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">Mirá los distintos rubros de los comercios aheridos que tenemos para vos!</h2>
                        <hr class="divider divider-light" />
                        <!--<p class="text-white-75 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
                        <a class="btn btn-light btn-xl" href="#services">Get Started!</a>-->
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/1.jpg' %}" title="Indumentaria">
                            <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/1.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Rubro</div>
                                <div class="project-name">Indumentaria</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/2.jpg' %}" title="Calzado">
                            <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/2.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Rubro</div>
                                <div class="project-name">Calzado</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/3.jpg' %}" title="Deportes">
                            <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/3.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Rubro</div>
                                <div class="project-name">Deportes</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/4.jpg' %}" title="Electrodomésticos">
                            <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/4.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Rubro</div>
                                <div class="project-name">Electrodomésticos</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/5.jpg' %}" title="Dormitorio">
                            <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/5.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">Rubro</div>
                                <div class="project-name">Dormitorio</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'AppCreditos/assets/img/portfolio/fullsize/6.jpg' %}" title="Materiales">
                            <img class="img-fluid" src="{% static 'AppCreditos/assets/img/portfolio/thumbnails/6.jpg' %}" alt="..." />
                            <div class="portfolio-box-caption p-3">
                                <div class="project-category text-white-50">Rubro</div>
                                <div class="project-name">Materiales</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
       
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2022 - Carlos Quinteros</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppCreditos/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>